sudo: false

language: node_js
node_js:
- '6'
- '8'
- '9'
- '10'
- '11'

cache:
  directories:
    - node_modules

script:
  - npm test

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5
